ALTER TABLE users DROP COLUMN IF EXISTS avatar_updated_at;
ALTER TABLE users DROP COLUMN IF EXISTS avatar_type;
ALTER TABLE users DROP COLUMN IF EXISTS avatar;
ALTER TABLE space DROP COLUMN IF EXISTS icon_updated_at;
ALTER TABLE space DROP COLUMN IF EXISTS icon_type;
ALTER TABLE space DROP COLUMN IF EXISTS icon;
